---
name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: kitforbes/epubcheck

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:$(date +%s)

      - name: Display Docker images
        run: docker images
